trigger:
- '*'

stages:
- stage: Build
  variables:
    dotnetSdkVersion: 3.1.300
    BuildConfiguration: release
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK $(dotnetSdkVersion)
      inputs:
        version: $(dotnetSdkVersion)
    - task: Npm@1
      displayName: Run npm install
      inputs:
        verbose: false

- stage: Deploy
  displayName: Deploy the web application
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: bba12a48-76de-4498-b0bf-77e7ce1d2b58
              appName: $(WebAppName)
              package: $(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip
