trigger:
- '*'

stages:
- stage: Build
  variables:
    dotnetSdkVersion: 3.1.300
    BuildConfiguration: release
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK $(dotnetSdkVersion)
      inputs:
        version: $(dotnetSdkVersion)
    - task: Npm@1
      displayName: Run npm install
      inputs:
        verbose: false
    - script: C:/ws-proj/CadastroLogin/src/main --output src/main
      displayName: Compile Sass assets
    - task: gulp@1
      displayName: Run gulp tasks
    - script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt
      displayName: Write build info
      workingDirectory: src/main

- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: deploy
    displayName: Deploy job
    environment: 'dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy Dev'
