trigger:
- '*'

stages:
- stage: Build
  variables:
    BuildConfiguration: release
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

- stage: Deploy
  displayName: Deploy
  jobs:
  - deployment: deploy
    displayName: Deploy job
    environment: 'dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'Deploy Dev'